package com.se.mapping;

// Generated Mar 16, 2015 10:31:49 AM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * TblSeUsers generated by hbm2java
 */
public class TblSeUsers implements java.io.Serializable
{

	private long id;
	private TblSeFunctions tblSeFunctions;
	private String userName;
	private String password;
	private long role;
	private Date insertionDate;

	public TblSeUsers()
	{
	}

	public TblSeUsers(long id, String userName)
	{
		this.id = id;
		this.userName = userName;
	}

	public TblSeUsers(long id, TblSeFunctions tblSeFunctions, String userName, String password,
			long role, Date insertionDate)
	{
		this.id = id;
		this.tblSeFunctions = tblSeFunctions;
		this.userName = userName;
		this.password = password;
		this.role = role;
		this.insertionDate = insertionDate;
	}

	public long getId()
	{
		return this.id;
	}

	public void setId(long id)
	{
		this.id = id;
	}

	public TblSeFunctions getTblSeFunctions()
	{
		return this.tblSeFunctions;
	}

	public void setTblSeFunctions(TblSeFunctions tblSeFunctions)
	{
		this.tblSeFunctions = tblSeFunctions;
	}

	public String getUserName()
	{
		return this.userName;
	}

	public void setUserName(String userName)
	{
		this.userName = userName;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public long getRole()
	{
		return this.role;
	}

	public void setRole(long role)
	{
		this.role = role;
	}

	public Date getInsertionDate()
	{
		return this.insertionDate;
	}

	public void setInsertionDate(Date insertionDate)
	{
		this.insertionDate = insertionDate;
	}

}
