package com.se.mapping;

// Generated Mar 16, 2015 10:31:49 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblSeFunctions generated by hbm2java
 */
public class TblSeFunctions implements java.io.Serializable
{

	private Long id;
	private String funName;
	private Date insertionDate;
	private Set tblSeUserses = new HashSet(0);

	public TblSeFunctions()
	{
	}

	public TblSeFunctions(Long id, String funName)
	{
		this.id = id;
		this.funName = funName;
	}

	public TblSeFunctions(Long id, String funName, Date insertionDate, Set tblSeUserses)
	{
		this.id = id;
		this.funName = funName;
		this.insertionDate = insertionDate;
		this.tblSeUserses = tblSeUserses;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getFunName()
	{
		return this.funName;
	}

	public void setFunName(String funName)
	{
		this.funName = funName;
	}

	public Date getInsertionDate()
	{
		return this.insertionDate;
	}

	public void setInsertionDate(Date insertionDate)
	{
		this.insertionDate = insertionDate;
	}

	public Set getTblSeUserses()
	{
		return this.tblSeUserses;
	}

	public void setTblSeUserses(Set tblSeUserses)
	{
		this.tblSeUserses = tblSeUserses;
	}

}
